#ifndef E_RESOURCE_EXPORT_H
#define E_RESOURCE_EXPORT_H

extern char _binary_shaders_model_frag_spv_end;
extern int _binary_shaders_model_frag_spv_size;
extern char _binary_shaders_model_frag_spv_start;
extern char _binary_shaders_model_vert_spv_end;
extern int _binary_shaders_model_vert_spv_size;
extern char _binary_shaders_model_vert_spv_start;
extern char _binary_shaders_model_shadow_frag_spv_end;
extern int _binary_shaders_model_shadow_frag_spv_size;
extern char _binary_shaders_model_shadow_frag_spv_start;
extern char _binary_shaders_model_shadow_vert_spv_end;
extern int _binary_shaders_model_shadow_vert_spv_size;
extern char _binary_shaders_model_shadow_vert_spv_start;

extern char _binary_shaders_text_frag_spv_end;
extern int _binary_shaders_text_frag_spv_size;
extern char _binary_shaders_text_frag_spv_start;
extern char _binary_shaders_text_vert_spv_end;
extern int _binary_shaders_text_vert_spv_size;
extern char _binary_shaders_text_vert_spv_start;

extern char _binary_shaders_default_frag2D_spv_end;
extern int _binary_shaders_default_frag2D_spv_size;
extern char _binary_shaders_default_frag2D_spv_start;
extern char _binary_shaders_default_vert2D_spv_end;
extern int _binary_shaders_default_vert2D_spv_size;
extern char _binary_shaders_default_vert2D_spv_start;

extern char _binary_shaders_default_frag3D_spv_end;
extern int _binary_shaders_default_frag3D_spv_size;
extern char _binary_shaders_default_frag3D_spv_start;
extern char _binary_shaders_default_vert3D_spv_end;
extern int _binary_shaders_default_vert3D_spv_size;
extern char _binary_shaders_default_vert3D_spv_start;

extern char _binary_shaders_quad_frag_spv_end;
extern int _binary_shaders_quad_frag_spv_size;
extern char _binary_shaders_quad_frag_spv_start;
extern char _binary_shaders_quad_frag_2_spv_end;
extern int _binary_shaders_quad_frag_2_spv_size;
extern char _binary_shaders_quad_frag_2_spv_start;
extern char _binary_shaders_quad_frag_3_spv_end;
extern int _binary_shaders_quad_frag_3_spv_size;
extern char _binary_shaders_quad_frag_3_spv_start;
extern char _binary_shaders_quad_vert_spv_end;
extern int _binary_shaders_quad_vert_spv_size;
extern char _binary_shaders_quad_vert_spv_start;