#ifndef E_RESOURCE_EXPORT_H
#define E_RESOURCE_EXPORT_H

extern char _binary_shaders_model_frag_spv_end;
extern int _binary_shaders_model_frag_spv_size;
extern char _binary_shaders_model_frag_spv_start;
extern char _binary_shaders_model_vert_spv_end;
extern int _binary_shaders_model_vert_spv_size;
extern char _binary_shaders_model_vert_spv_start;
extern char _binary_shaders_model_shadow_frag_spv_end;
extern int _binary_shaders_model_shadow_frag_spv_size;
extern char _binary_shaders_model_shadow_frag_spv_start;
extern char _binary_shaders_model_shadow_vert_spv_end;
extern int _binary_shaders_model_shadow_vert_spv_size;
extern char _binary_shaders_model_shadow_vert_spv_start;

extern char _binary_shaders_text_frag_spv_end;
extern int _binary_shaders_text_frag_spv_size;
extern char _binary_shaders_text_frag_spv_start;
extern char _binary_shaders_text_vert_spv_end;
extern int _binary_shaders_text_vert_spv_size;
extern char _binary_shaders_text_vert_spv_start;

extern char _binary_shaders_default_frag2D_spv_end;
extern int _binary_shaders_default_frag2D_spv_size;
extern char _binary_shaders_default_frag2D_spv_start;
extern char _binary_shaders_default_vert2D_spv_end;
extern int _binary_shaders_default_vert2D_spv_size;
extern char _binary_shaders_default_vert2D_spv_start;

extern char _binary_shaders_default_frag3D_spv_end;
extern int _binary_shaders_default_frag3D_spv_size;
extern char _binary_shaders_default_frag3D_spv_start;
extern char _binary_shaders_default_vert3D_spv_end;
extern int _binary_shaders_default_vert3D_spv_size;
extern char _binary_shaders_default_vert3D_spv_start;

extern char _binary_shaders_quad_frag_spv_end;
extern int _binary_shaders_quad_frag_spv_size;
extern char _binary_shaders_quad_frag_spv_start;
extern char _binary_shaders_quad_frag_2_spv_end;
extern int _binary_shaders_quad_frag_2_spv_size;
extern char _binary_shaders_quad_frag_2_spv_start;
extern char _binary_shaders_quad_frag_3_spv_end;
extern int _binary_shaders_quad_frag_3_spv_size;
extern char _binary_shaders_quad_frag_3_spv_start;
extern char _binary_shaders_quad_vert_spv_end;
extern int _binary_shaders_quad_vert_spv_size;
extern char _binary_shaders_quad_vert_spv_start;

extern char _binary_shaders_depth_frag_spv_end;
extern int _binary_shaders_depth_frag_spv_size;
extern char _binary_shaders_depth_frag_spv_start;
extern char _binary_shaders_depth_vert_spv_end;
extern int _binary_shaders_depth_vert_spv_size;
extern char _binary_shaders_depth_vert_spv_start;

extern char _binary_shaders_geometry_frag_spv_end;
extern int _binary_shaders_geometry_frag_spv_size;
extern char _binary_shaders_geometry_frag_spv_start;
extern char _binary_shaders_geometry_vert_spv_end;
extern int _binary_shaders_geometry_vert_spv_size;
extern char _binary_shaders_geometry_vert_spv_start;

extern char _binary_shaders_depth_frag_omni_spv_end;
extern int _binary_shaders_depth_frag_omni_spv_size;
extern char _binary_shaders_depth_frag_omni_spv_start;
extern char _binary_shaders_depth_vert_omni_spv_end;
extern int _binary_shaders_depth_vert_omni_spv_size;
extern char _binary_shaders_depth_vert_omni_spv_start;

extern char _binary_shaders - depth_frag_spot_spv_end;
extern int _binary_shaders_depth_frag_spot_spv_size;
extern char _binary - shaders_depth - frag_spot_spv_start;
extern char _binary_depth_vert_spot_spv_end;
extern int _binary_shaders_depth_vert_spot_spv_size;
extern char - binary_shaders_depth_vert_spot_spv_start;

extern char _binary_shaders_terrain_frag_spv_end;
extern int  _binary_shaders_terrain_frag_spv_size;
extern char _binary_shaders_terrain_frag_spv_start;
extern char _binary_shaders_terrain_vert_spv_end;
extern int _binary_shaders_terrain_vert_spv_size;
extern char _binary_shaders_terrain_vert_spv_start;
extern char _binary_shaders_terrain_stesc_spv_end;
extern int _binary_shaders_terrain_tesc_spv_size;
extern char _binary_shaders_terrain_tesc_spv_start;
extern char _binary_shaders_terrain_tese_spv_end;
extern int _binary_shaders_terrain_tese_spv_end;
extern char _binary_shaders_terrain_tese_spv_start;
extern char _binary_shaders_terrain_shadow_frag_spv_end;
extern int _binary_shaders_terrain_shadow_frag_spv_size;
extern char _binary_shaders_terrain_shadow_frag_spv_start;
extern char _binary_shaders_terrain_shadow_vert_spv_end;
extern int _binary_shaders_terrain_shadow_vert_spv_size;
extern char _binary_shaders_terrain_shadow_vert_spv_start;

extern char _binary_shaders_terrain_shadow_tree_frag_spv_end;
extern int _binary_shaders_tree_frag_spv_size;
extern char _binary_shaders_treee_frag_spv_start;
extern char _binary_shaders_tree_vert_spv_end;
extern int binary_shaders_tree_vert_spv_size;
extern char _binary_shaders_treee_vert_spv_start;

extern char _binary_shaders_tree_instance_frag_spv_end;
extern int _binary_shaders_tree_instance_frag_spv_size;
extern char _binary_shaders_tree_instance_frag_spv_start;
extern char _binary_shaders_tree_instance_vert_spv_end;
extern int - binary - shaders_tree_instance_vert_spv_size;
extern char _binary_shaders_tree_instance_vert_spv_start;

extern char _binary_shaders_tree_sdf_frag_spv_end;
extern int _binary_shadows_tree_sf_frag_spv_size;
extern char _binary_shaders_tree_sdf_frag_spv_start;
extern char _binary_shaders_tree_sdf_vert_spv_end;
extern int _binary_shaders_tree_sdf_vert_spv_size;
extern char _binary_shaders_tree_sdf_vert_spv_start;
extern char _binary_shaders_tree_sdf_vert_spv_end;

extern char _binary_shaders_image_frag_spv_end;
extern int _binary_shaders_image_frag_spv_size;
extern char _binary_shaders_image_frag_spv_start;
extern char _binary_shaders_image_vert_spv_end;
extern int _binary_shaders_image_vert_spv_size;
extern char _binary_shaders_image_vert_spv_start;