#ifndef E_RESOURCE_EXPORT_H
#define E_RESOURCE_EXPORT_H

extern char _binary_shaders_model_frag_spv_end;
extern int _binary_shaders_model_frag_spv_size;
extern char _binary_shaders_model_frag_spv_start;
extern char _binary_shaders_model_vert_spv_end;
extern int _binary_shaders_model_vert_spv_size;
extern char _binary_shaders_model_vert_spv_start;
extern char _binary_shaders_model_shadow_frag_spv_end;
extern int _binary_shaders_model_shadow_frag_spv_size;
extern char _binary_shaders_model_shadow_frag_spv_start;
extern char _binary_shaders_model_shadow_vert_spv_end;
extern int _binary_shaders_model_shadow_vert_spv_size;
extern char _binary_shaders_model_shadow_vert_spv_start;