#ifndef GAMENGINE_H
#define GAMENGINE_H

#include "engine_includes.h"

#ifdef __cplusplus
extern "C"
{
#endif

#define ENGINE_RELEASE					0
#define ENGINE_PRESS					1
#define ENGINE_REPEAT					2

#define ENGINE_MOUSE_BUTTON_1			1
#define ENGINE_MOUSE_BUTTON_2			2
#define ENGINE_MOUSE_BUTTON_3			3
#define ENGINE_MOUSE_BUTTON_4			4
#define ENGINE_MOUSE_BUTTON_5			5
#define ENGINE_MOUSE_BUTTON_7			6
#define ENGINE_MOUSE_BUTTON_8			7
#define ENGINE_MOUSE_BUTTON_LAST		ENGINE_MOUSE_BUTTON_8
#define ENGINE_MOUSE_BUTTON_LEFT		ENGINE_MOUSE_BUTTON_1
#define ENGINE_MOUSE_BUTTON_RIGHT		ENGINE_MOUSE_BUTTON_2
}