#ifndef SHADER_BUILDER_H
#define SHADER_BUILDER_H

#include <stdint.h>

#define EXTERN_IMPORT_POINT_INDEX 0x1

#define SHADER_MAX_LENGTH 2048
#define SHADER_MAX_IODATA 32
#define SHADER_MAX_VARIABLES 256
#define SHADER_MAX_DEBUG_NAMES 256
#define SHADER_MAX_FUNCTIONS 32
#define SHADER_MAX_DECORATIONS 32

typedef enum
{
	SHADER_TYPE_FRAGMENT,
	SHADER_TYPE_VERTEX,
	SHADER_TYPE_COMPUTED,
	SHADER_TYPE_GEOMETRY,
	SHADER_TYPE_TESELLATION_CONTROL,
	SHADER_TYPE_TESELLATION_EVALUATION,
} ShaderType;